#lang racket
(define (make-account balance password)
  (define (withdraw amount)
    (if (<= amount balance)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch pwd m)
    (cond ((not (eq? pwd password)) (lambda (x) "Incorrect password"))
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (lambda (x) "Invalid message"))))
  dispatch)

(define acc (make-account 200 'anirudh))
(eq? ((acc 'a 'withdrawal) 50) "Incorrect password")
(eq? ((acc 'anirudh 'withdrawal) 50) "Invalid message")
(eq? ((acc 'anirudh 'withdraw) 500) "Insufficient funds")
(eq? ((acc 'anirudh 'withdraw) 50) 150)
(eq? ((acc 'anirudh 'deposit) 50) 200)